# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HTR United Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install htr-united-metadata-generator htruc
    - name: Run Report
      run: |
        humGenerator --group ./data/**/*.xml --github-envs --to-json updated_metrics.json
        cat envs.txt >> $GITHUB_ENV
    - name: Automatically update the catalog's volume key
      run: |
        htruc update-volumes htr-united.yml updated_metrics.json --inplace
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add htr-united.yml
        git commit -m "[Automatic] Update of the Catalog" || echo "Nothing to commit"
        git push